{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Tranquilify server API",
    "description" : "API for Tranquilify's server",
    "contact" : {
      "email" : "wagenheimj@moravian.edu"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/itchybarn/Headphones-Server/1.0.0",
    "description" : "SwaggerHub API Auto Mocking"
  } ],
  "tags" : [ {
    "name" : "users",
    "description" : "Available to all users"
  } ],
  "paths" : {
    "/login" : {
      "post" : {
        "tags" : [ "users" ],
        "summary" : "user login",
        "description" : "By passing in a username and password, the user can attempt\nto login\n",
        "operationId" : "loginUser",
        "requestBody" : {
          "description" : "Login credentials",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/LoginCredentials"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "successful login",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/SessionToken"
                }
              }
            }
          },
          "400" : {
            "description" : "bad input parameter"
          },
          "401" : {
            "description" : "invalid username or password"
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "LoginCredentials" : {
        "required" : [ "password", "username" ],
        "type" : "object",
        "properties" : {
          "username" : {
            "type" : "string",
            "description" : "username with which the user is attempting to log in"
          },
          "password" : {
            "type" : "string",
            "description" : "password with which the user is attempting to log in",
            "format" : "password"
          }
        }
      },
      "SessionToken" : {
        "type" : "object",
        "properties" : {
          "token" : {
            "type" : "string"
          }
        }
      }
    }
  }
}