{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Tranquilify server API",
    "description" : "API for Tranquilify's server",
    "contact" : {
      "email" : "wagenheimj@moravian.edu"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/itchybarn/Headphones-Server/1.0.0",
    "description" : "SwaggerHub API Auto Mocking"
  } ],
  "tags" : [ {
    "name" : "users",
    "description" : "Available to all users"
  } ],
  "paths" : {
    "/login" : {
      "post" : {
        "tags" : [ "users" ],
        "summary" : "user login",
        "description" : "By passing in a username and password, the user can attempt\nto login\n",
        "operationId" : "loginUser",
        "requestBody" : {
          "description" : "Login credentials",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/LoginCredentials"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "successful login",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/SessionToken"
                }
              }
            }
          },
          "400" : {
            "description" : "bad input parameter"
          },
          "403" : {
            "description" : "invalid username or password"
          }
        }
      }
    },
    "/user" : {
      "post" : {
        "tags" : [ "users" ],
        "summary" : "create new user",
        "description" : "Creates a new user with a given username and password\n",
        "operationId" : "createUser",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/UserCreationComponent"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "successful user creation"
          },
          "400" : {
            "description" : "bad input parameter"
          },
          "403" : {
            "description" : "unsuccessful user creation"
          }
        }
      }
    },
    "/username" : {
      "get" : {
        "tags" : [ "users" ],
        "summary" : "get current user's username",
        "description" : "Returns the username of the currently logged-in user. Identifies\nthe user through the bearer token sent through the Authorization\nheader received from /login\n",
        "operationId" : "getCurrentUsername",
        "responses" : {
          "200" : {
            "description" : "authenticated user's username",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Username"
                }
              }
            }
          },
          "400" : {
            "description" : "bad input parameter"
          },
          "401" : {
            "description" : "missing or invalid token"
          }
        },
        "security" : [ {
          "bearerAuth" : [ ]
        } ]
      }
    },
    "/auth" : {
      "get" : {
        "tags" : [ "users" ],
        "summary" : "send a code to the user",
        "description" : "Sends a code to the currently logged-in user's\nauthentication method\n",
        "operationId" : "runAuth",
        "responses" : {
          "200" : {
            "description" : "authentication sent successfully"
          },
          "400" : {
            "description" : "bad input parameter"
          },
          "401" : {
            "description" : "missing or invalid token"
          },
          "403" : {
            "description" : "was not able to send authentication"
          }
        },
        "security" : [ {
          "bearerAuth" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "users" ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/AuthAttempt"
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "successful authentication"
          },
          "400" : {
            "description" : "bad input parameter"
          },
          "401" : {
            "description" : "missing or invalid token"
          },
          "403" : {
            "description" : "unsuccessful authentication"
          }
        },
        "security" : [ {
          "bearerAuth" : [ ]
        } ]
      }
    }
  },
  "components" : {
    "schemas" : {
      "UserCreationComponent" : {
        "required" : [ "authMethod", "loginCredentials" ],
        "type" : "object",
        "properties" : {
          "loginCredentials" : {
            "$ref" : "#/components/schemas/LoginCredentials"
          },
          "authMethod" : {
            "$ref" : "#/components/schemas/AuthMethod"
          }
        }
      },
      "LoginCredentials" : {
        "required" : [ "password", "username" ],
        "type" : "object",
        "properties" : {
          "username" : {
            "$ref" : "#/components/schemas/Username"
          },
          "password" : {
            "$ref" : "#/components/schemas/Password"
          }
        }
      },
      "SessionToken" : {
        "type" : "object",
        "properties" : {
          "token" : {
            "type" : "string"
          },
          "timestamp" : {
            "type" : "string",
            "format" : "date-time"
          }
        }
      },
      "Username" : {
        "type" : "string",
        "example" : "username"
      },
      "Password" : {
        "type" : "string",
        "description" : "password with which the user is attempting to log in",
        "format" : "password"
      },
      "AuthMethod" : {
        "type" : "string",
        "example" : "1235557890"
      },
      "AuthAttempt" : {
        "type" : "string",
        "example" : "1234"
      }
    },
    "securitySchemes" : {
      "bearerAuth" : {
        "type" : "http",
        "scheme" : "bearer",
        "bearerFormat" : "JWT"
      }
    }
  }
}